apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: paloalto_monitoring
    user: collector
    secureJsonData:
      password: eSJmY4mNBhtQb8hA
    isDefault: true
    editable: true